erDiagram
    Address {
        Guid AddressId
        string StreetAddress
        string SuburbName
        string CityName
        string Province
        decimal Longitude
        decimal Latitude
    }

    ApplicationUser {
        string Id
    }

    AuthorisationType {
        Guid AuthorisationTypeId
        string AuthorisationTypeName
        string AuthorisationTypedescription
    }

    Crop {
        Guid CropId
        string CropName
        Guid CropTypeId
    }

    CropType {
        Guid CropTypeId
        string CropTypeName
        string CropTypeDecription
    }

    CustomerTitle {
        enum "Mr"
        enum "Miss"
        enum "Mrs"
        enum "Dr"
        enum "Prof"
        enum "Pastor"
    }

    CustomerType {
        Guid Id
        string CustomerTypeName
    }

    DamCalculation {
        Guid DamCalculationId
        DateOnly CalculationDate
        Guid PropertyId
        string SateliteQualifyPeriod
        DateOnly SateliteSurveyDate
        string DamNumber
        decimal DamCapacity
        Guid RiverId
        DamCalculationStatus DamCalculationStatus
    }

    DamCalculationStatus {
        enum "COMPLETED"
        enum "IN_PROGRESS"
        enum "CANCELLED"
    }

    Entitlement {
        Guid EntitlementId
        string Name
        decimal Volume
    }

    EntitlementType {
        Guid EntitlementTypeId
        string EntitlementName
        string EntitlementDescription
    }

    FieldAndCrop {
        Guid FieldAndCropId
        Guid PropertyId
        Guid PeriodId
        string FieldNumber
        decimal FieldArea
        Guid CropId
        DateOnly PlantDate
        decimal RotationFactor
        Guid IrrigationSystemId
        Guid WaterSourceId
        decimal CropArea
        decimal SAPWATCalculationResult
        Guid EntitlementId
    }

    FileMaster {
        Guid Id
        string RegistrationNumber
        Guid PropertyAddressId
        string SurveyorGeneralCode
        string PrimaryCatchment
        string QuaternaryCatchment
        string FarmName
        int FarmNumber
        string RegistrationDivision
        string FarmPortion
        string Notes
        decimal Latitude
        decimal Longitude
        string NameUpdate
        string PropertyIndex
        string RegistrationStatusPrePublicParticipation
        string RegistrationStatusPostPublicParticipation
        string WarmsApplicant
        string FileNumber
        DateOnly FileCreatedDate
        string FileStatus
        string RequirementDescription
        string WARMSPrintsReceived
        string Group
        string LegalTypeGroup
        string RiparianFarm
        bool RegisteredForTakingWater
        bool RegiteredForStoring
        bool RegisteredForForestation
        string BatchDescription
        string LatestLetterTypeIssued
        ValidationStatus GetValidationStatus
        string ValidationPersonId
        DateOnly ValidationStartDate
        string ValidationDescription
        string CapturePersonId
        int MyProperty
    }

    Forestation {
        Guid ForestationId
        Guid PropertyId
        bool WithinGWCA
        decimal QualifyPeriodSFRAHectares
        decimal CurrentPeriodSFRAHectares
        decimal QualifyPeriodVolume
        string Specie
        string WaterResource
        decimal RegisteredHectares
        decimal RegisteredVolume
        string UserFeedbackEntitlementType
        string UserFeedbackEntitlementReference
        decimal UserFeedbackEntitlementHectares
        string CommentOnFeedback
        decimal ELUHectares
        decimal ELUVolume
        decimal UnlawfulHectares
        decimal UnlawfulVolume
        decimal LawfulHectares
        decimal LawfulVolume
        string UnitForVolumeCalculation
        decimal Pre1972Hectares
        decimal Pre1972Volume
        string SFRAPermitNumber
        decimal SFRAPermitHectares
        string CommentsOnData
        Guid EntitlementId
    }

    Gender {
        enum "MALE"
        enum "FEMALE"
        enum "OTHER"
    }

    GovernmentWaterControlArea {
        Guid WaterControlAreaId
        string GovernmentWaterControlAreaName
        Guid WaterControlAddressId
        string WaterControlPhoneNumber
    }

    GovernmentWaterScheme {
        Guid WaterSchemeId
        string WaterSchemeName
    }

    Irrigation {
        Guid IrrigationId
        string IrrigationName
        Guid PropertyId
        DateOnly WaterDate
        decimal WaterVolume
        decimal WaterLandArea
        decimal WaterCropArea
        Guid WaterSourceId
    }

    IrrigationBoard {
        Guid IrrigationBoardId
        string IrrigationBoardName
        string IrrigationBoardPNumber
        string EmailAddress
        Guid IrrigationBoardAddressId
    }

    IrrigationSystem {
        Guid IrrigationSystemId
        string IrrigationSystemName
        string IrrigationSystemDescription
        string IrrigationSystemModel
    }

    IssuedLetters {
        Guid Id
    }

    LetterIssuance {
        Guid Id
        Guid PropertyOwnerId
        Guid LetterTypeId
        DateOnly LetterDate
    }

    LetterType {
        Guid Id
        string LetterName
        string LetterDescription
    }

    Period {
        Guid PeriodId
        string PeriodName
    }

    Property {
        Guid PropertyId
        string PropertyReferenceNumber
        Guid PropertyAddressId
        int PropertySize
        DateOnly ProclamationDate
        DateOnly RegistrationDate
        string SGCode
        string QuatenaryDrainage
        string WaterManagementArea
        decimal Longitude
        decimal Latitude
        Guid EntitlementId
    }

    PropertyOwner {
        Guid OwnerId
        string FirstName
        string LastName
        DateOnly DateOfBirth
        Guid CustomerTypeId
        CustomerTitle CustomerTitle
        int IdentityDocumentNumber
        string EmailAddress
        Guid AddressId
        Gender OwnerGender
    }

    PropertyOwnership {
        Guid Id
        Guid PropertyId
        Guid PropertyOwnerId
        string TitleDeedNumber
        DateOnly TitleDeedDate
    }

    River {
        Guid RiverId
        string RiverName
    }

    SateliteImage {
        Guid ImageId
        string ImageName
        string FarmNumber
        DateOnly MapCompilation
        DateOnly ImageDate
        string ImageNumber
    }

    VerifactionScenario {
        enum "PROCLAMATION_DATE"
        enum "POSSIBLE_EXISTING"
        enum "POSSIBLE_LAWFUL"
        enum "POSSIBLE_UNLAWFUL"
        enum "REGISTERED"
        enum "PRESENT"
        enum "PRESENT_POSSIBLE"
        enum "GENERAL_AUTHORISATION"
    }

    Storing {
        Guid StoringId
        Guid PropertyId
        int NumberOfDams
        decimal Volume
        Guid RiverOrStreamId
        VerifactionScenario VerifactionScenario
        Guid PeriodId
    }

    Validation {
        Guid Id
        ValidationStatus ValidationStatus
        DateOnly ValidationStartDate
        Guid PropertyId
        Guid PeriodId
        Guid EntitlementId
    }

    ValidationStatus {
        enum "EVALAUTE_ADDTIONAL_INFORMATION"
        enum "CALCULATE_ELU_DISCREPANCY"
        enum "GIS_ANALYSIS_AND_FIELD_DIGITISING"
        enum "FIELD_AND_CROP_MODELLING"
        enum "UPDATE_VANDV_DATABASE"
        enum "CALCULATE_DAM_VOLUMES"
        enum "CALCULATE_STREAM_FLOW_REDUCTION"
        enum "IDENTIFY_UNREGISTERED_USERS"
        enum "VANDV_DATABASE_ANALYSIS_TO_IDENTIFY_RECORD_STATUS"
        enum "PROJECT_INCEPTION_REPORT"
        enum "PUBLIC_PARTICIPATION_SESSIONS"
        enum "EVALUATE_WARMS_REGISTRATION_INFORMATION"
        enum "OBTAIN_SUPPORTIVE_SPATIAL_INFORMATION"
        enum "OBTAIN_OTHER_SUPPORTIVR_INFORMATION"
        enum "PROPERTY_AND_SOURCE_EVALUATION"
    }

    WaterSource {
        Guid WaterSourceId
        string WaterSourceName
        WaterSourceType WaterSourceType
    }

    WaterSourceType {
        enum "SURFACE"
        enum "BOREHOLE"
        enum "STREAM"
    }
    
    Property ||--o{ PropertyOwnership : "has"
    PropertyOwner ||--o{ PropertyOwnership : "owns"
    Property }o--|| Address : "located at"
    Property }o--|| Entitlement : "has"
    PropertyOwner }o--|| Address : "resides at"
    PropertyOwner }o--|| CustomerType : "is a"
    DamCalculation }o--|| Property : "is for"
    DamCalculation }o--|| River : "is on"
    FieldAndCrop }o--|| Property : "is on"
    FieldAndCrop }o--|| Period : "is for"
    FieldAndCrop }o--|| Crop : "grows"
    FieldAndCrop }o--|| IrrigationSystem : "uses"
    FieldAndCrop }o--|| WaterSource : "uses"
    FieldAndCrop }o--|| Entitlement : "consumes"
    Forestation }o--|| Property : "is on"
    Forestation }o--|| Entitlement : "relates to"
    Irrigation }o--|| Property : "is for"
    Irrigation }o--|| WaterSource : "uses"
    Storing }o--|| Property : "is on"
    Storing }o--|| River : "is on"
    Storing }o--|| Period : "is for"
    LetterIssuance }o--|| PropertyOwner : "is for"
    LetterIssuance }o--|| LetterType : "is of type"
    Validation }o--|| Property : "validates"
    Validation }o--|| Period : "is for"
    Validation }o--|| Entitlement : "validates"
    Crop ||--|{ CropType : "is a"
    WaterSource ||--|{ WaterSourceType : "is of type"
    GovernmentWaterControlArea }o--|| Address : "is at"
    IrrigationBoard }o--|| Address : "is at"
    FileMaster }o--|| ApplicationUser : "validated by"
    FileMaster }o--|| ApplicationUser : "captured by"
    FileMaster }o--|| ValidationStatus : "has status"
    PropertyOwner ||--|{ CustomerTitle : "has title"
    PropertyOwner ||--|{ Gender : "is"
    DamCalculation ||--|{ DamCalculationStatus : "has status"
    Storing ||--|{ VerifactionScenario : "has scenario"
    Validation ||--|{ ValidationStatus : "has status"
    WaterSource ||--|{ WaterSourceType : "is type"
