// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace dwa_ver_val.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    partial class ApplicationDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Address", b =>
                {
                    b.Property<Guid>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("decimal(9, 6)");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("decimal(9, 6)");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SuburbName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AddressId");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ApplicationUsers");
                });

            modelBuilder.Entity("AuthorisationType", b =>
                {
                    b.Property<Guid>("AuthorisationTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AuthorisationTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AuthorisationTypedescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AuthorisationTypeId");

                    b.ToTable("AuthorisationTypes");
                });

            modelBuilder.Entity("Crop", b =>
                {
                    b.Property<Guid>("CropId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CropName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("CropTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CropId");

                    b.HasIndex("CropTypeId");

                    b.ToTable("Crops");
                });

            modelBuilder.Entity("CropType", b =>
                {
                    b.Property<Guid>("CropTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CropTypeDecription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CropTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CropTypeId");

                    b.ToTable("CropTypes");
                });

            modelBuilder.Entity("CustomerType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CustomerTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CustomerTypes");
                });

            modelBuilder.Entity("DamCalculation", b =>
                {
                    b.Property<Guid>("DamCalculationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("CalculationDate")
                        .HasColumnType("date");

                    b.Property<decimal>("DamCapacity")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("DamNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RiverId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SateliteQualifyPeriod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("SateliteSurveyDate")
                        .HasColumnType("date");

                    b.HasKey("DamCalculationId");

                    b.HasIndex("PropertyId");

                    b.HasIndex("RiverId");

                    b.ToTable("DamCalculations");
                });

            modelBuilder.Entity("Entitlement", b =>
                {
                    b.Property<Guid>("EntitlementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EntitlementId");

                    b.ToTable("Entitlements");
                });

            modelBuilder.Entity("EntitlementType", b =>
                {
                    b.Property<Guid>("EntitlementTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EntitlementDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntitlementName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EntitlementTypeId");

                    b.ToTable("EntitlementTypes");
                });

            modelBuilder.Entity("FieldAndCrop", b =>
                {
                    b.Property<Guid>("FieldAndCropId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("CropArea")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<Guid>("CropId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("FieldArea")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("FieldNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("IrrigationSystemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PeriodId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly?>("PlantDate")
                        .HasColumnType("date");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("RotationFactor")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("SAPWATCalculationResult")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<Guid>("WaterSourceId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("FieldAndCropId");

                    b.HasIndex("CropId");

                    b.HasIndex("IrrigationSystemId");

                    b.HasIndex("PeriodId");

                    b.HasIndex("PropertyId");

                    b.HasIndex("WaterSourceId");

                    b.ToTable("FieldAndCrops");
                });

            modelBuilder.Entity("FileMaster", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BatchDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CapturePersonId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FarmName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FarmNumber")
                        .HasColumnType("int");

                    b.Property<string>("FarmPortion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("FileCreatedDate")
                        .HasColumnType("date");

                    b.Property<string>("FileNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GetValidationStatus")
                        .HasColumnType("int");

                    b.Property<string>("Group")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LatestLetterTypeIssued")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("decimal(9, 6)");

                    b.Property<string>("LegalTypeGroup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("decimal(9, 6)");

                    b.Property<int>("MyProperty")
                        .HasColumnType("int");

                    b.Property<string>("NameUpdate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrimaryCatchment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PropertyAddressId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PropertyIndex")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuaternaryCatchment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("RegisteredForForestation")
                        .HasColumnType("bit");

                    b.Property<bool?>("RegisteredForTakingWater")
                        .HasColumnType("bit");

                    b.Property<string>("RegistrationDivision")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegistrationStatusPostPublicParticipation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegistrationStatusPrePublicParticipation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("RegiteredForStoring")
                        .HasColumnType("bit");

                    b.Property<string>("RequirementDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RiparianFarm")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SurveyorGeneralCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ValidationDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ValidationPersonId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateOnly>("ValidationStartDate")
                        .HasColumnType("date");

                    b.Property<string>("WARMSPrintsReceived")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WarmsApplicant")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CapturePersonId");

                    b.HasIndex("PropertyAddressId")
                        .IsUnique();

                    b.HasIndex("ValidationPersonId");

                    b.ToTable("FileMasters");
                });

            modelBuilder.Entity("Forestation", b =>
                {
                    b.Property<Guid>("ForestationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CommentOnFeedback")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CommentsOnData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("CurrentPeriodSFRAHectares")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("ELUHectares")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("ELUVolume")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("LawfulHectares")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("LawfulVolume")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("Pre1972Hectares")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("Pre1972Volume")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("QualifyPeriodSFRAHectares")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("QualifyPeriodVolume")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("RegisteredHectares")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("RegisteredVolume")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("SFRAPermitHectares")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("SFRAPermitNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Specie")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnitForVolumeCalculation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("UnlawfulHectares")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("UnlawfulVolume")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("UserFeedbackEntitlementHectares")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("UserFeedbackEntitlementReference")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserFeedbackEntitlementType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WaterResource")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("WithinGWCA")
                        .HasColumnType("bit");

                    b.HasKey("ForestationId");

                    b.ToTable("Forestations");
                });

            modelBuilder.Entity("GovernmentWaterControlArea", b =>
                {
                    b.Property<Guid>("WaterControlAreaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GovernmentWaterControlAreaName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("WaterControlAddressAddressId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("WaterControlPhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("WaterControlAreaId");

                    b.HasIndex("WaterControlAddressAddressId");

                    b.ToTable("GovernmentWaterControlAreas");
                });

            modelBuilder.Entity("GovernmentWaterScheme", b =>
                {
                    b.Property<Guid>("WaterSchemeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("WaterSchemeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("WaterSchemeId");

                    b.ToTable("GovernmentWaterSchemes");
                });

            modelBuilder.Entity("Irrigation", b =>
                {
                    b.Property<Guid>("IrrigationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("IrrigationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("WaterCropArea")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateOnly>("WaterDate")
                        .HasColumnType("date");

                    b.Property<decimal>("WaterLandArea")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("WaterSourceType")
                        .HasColumnType("int");

                    b.Property<decimal>("WaterVolume")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("IrrigationId");

                    b.HasIndex("PropertyId");

                    b.ToTable("Irrigations");
                });

            modelBuilder.Entity("IrrigationBoard", b =>
                {
                    b.Property<Guid>("IrrigationBoardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EmailAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("IrrigationBoardAddressAddressId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("IrrigationBoardName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IrrigationBoardPNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IrrigationBoardId");

                    b.HasIndex("IrrigationBoardAddressAddressId");

                    b.ToTable("IrrigationBoards");
                });

            modelBuilder.Entity("IrrigationSystem", b =>
                {
                    b.Property<Guid>("IrrigationSystemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("IrrigationSystemDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IrrigationSystemModel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IrrigationSystemName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IrrigationSystemId");

                    b.ToTable("IrrigationSystems");
                });

            modelBuilder.Entity("IssuedLetters", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("IssuedLetters");
                });

            modelBuilder.Entity("LetterIssuance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("LetterDate")
                        .HasColumnType("date");

                    b.Property<Guid>("LetterTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PropertyOwnerOwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("LetterTypeId");

                    b.HasIndex("PropertyOwnerOwnerId");

                    b.ToTable("LetterIssuances");
                });

            modelBuilder.Entity("LetterType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LetterDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LetterName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LetterTypes");
                });

            modelBuilder.Entity("Period", b =>
                {
                    b.Property<Guid>("PeriodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PeriodName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PeriodId");

                    b.ToTable("Periods");
                });

            modelBuilder.Entity("Property", b =>
                {
                    b.Property<Guid>("PropertyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("decimal(9, 6)");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("decimal(9, 6)");

                    b.Property<DateOnly>("ProclamationDate")
                        .HasColumnType("date");

                    b.Property<Guid?>("PropertyAddressAddressId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PropertyNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PropertySize")
                        .HasColumnType("int");

                    b.Property<string>("QuatenaryDrainage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("RegistrationDate")
                        .HasColumnType("date");

                    b.Property<string>("SGCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WaterManagementArea")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PropertyId");

                    b.HasIndex("PropertyAddressAddressId");

                    b.ToTable("Properties");
                });

            modelBuilder.Entity("PropertyAddress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalAddress1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalAddress2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalAddress3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PropertyReference")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PropertyAddresses");
                });

            modelBuilder.Entity("PropertyOwner", b =>
                {
                    b.Property<Guid>("OwnerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AddressId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CustomerTitle")
                        .HasColumnType("int");

                    b.Property<Guid>("CustomerTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdentityDocumentNumber")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OwnerGender")
                        .HasColumnType("int");

                    b.HasKey("OwnerId");

                    b.HasIndex("AddressId");

                    b.HasIndex("CustomerTypeId");

                    b.ToTable("PropertyOwners");
                });

            modelBuilder.Entity("PropertyOwnership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PropertyOwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly?>("TitleDeedDate")
                        .HasColumnType("date");

                    b.Property<string>("TitleDeedNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId");

                    b.HasIndex("PropertyOwnerId");

                    b.ToTable("PropertyOwnerships");
                });

            modelBuilder.Entity("River", b =>
                {
                    b.Property<Guid>("RiverId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RiverName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RiverId");

                    b.ToTable("Rivers");
                });

            modelBuilder.Entity("SateliteImage", b =>
                {
                    b.Property<Guid>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FarmNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("ImageDate")
                        .HasColumnType("date");

                    b.Property<string>("ImageName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("MapCompilation")
                        .HasColumnType("date");

                    b.HasKey("ImageId");

                    b.ToTable("SateliteImages");
                });

            modelBuilder.Entity("Storing", b =>
                {
                    b.Property<Guid>("StoringId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("NumberOfDams")
                        .HasColumnType("int");

                    b.Property<Guid>("PeriodId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("RiverOrStreamRiverId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("VerifactionScenario")
                        .HasColumnType("int");

                    b.Property<decimal>("Volume")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("StoringId");

                    b.HasIndex("PeriodId");

                    b.HasIndex("PropertyId");

                    b.HasIndex("RiverOrStreamRiverId");

                    b.ToTable("Storings");
                });

            modelBuilder.Entity("Validation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Validations");
                });

            modelBuilder.Entity("WaterSource", b =>
                {
                    b.Property<Guid>("WaterSourceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("WaterSourceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WaterSourceType")
                        .HasColumnType("int");

                    b.HasKey("WaterSourceId");

                    b.ToTable("WaterSources");
                });

            modelBuilder.Entity("Crop", b =>
                {
                    b.HasOne("CropType", "CropType")
                        .WithMany()
                        .HasForeignKey("CropTypeId");

                    b.Navigation("CropType");
                });

            modelBuilder.Entity("DamCalculation", b =>
                {
                    b.HasOne("Property", "Property")
                        .WithMany()
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("River", "River")
                        .WithMany()
                        .HasForeignKey("RiverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Property");

                    b.Navigation("River");
                });

            modelBuilder.Entity("FieldAndCrop", b =>
                {
                    b.HasOne("Crop", "Crop")
                        .WithMany()
                        .HasForeignKey("CropId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IrrigationSystem", "IrrigationSystem")
                        .WithMany()
                        .HasForeignKey("IrrigationSystemId");

                    b.HasOne("Period", "Period")
                        .WithMany()
                        .HasForeignKey("PeriodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Property", "Property")
                        .WithMany()
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WaterSource", "WaterSource")
                        .WithMany()
                        .HasForeignKey("WaterSourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Crop");

                    b.Navigation("IrrigationSystem");

                    b.Navigation("Period");

                    b.Navigation("Property");

                    b.Navigation("WaterSource");
                });

            modelBuilder.Entity("FileMaster", b =>
                {
                    b.HasOne("ApplicationUser", "CapturePerson")
                        .WithMany()
                        .HasForeignKey("CapturePersonId");

                    b.HasOne("PropertyAddress", "PropertyAddress")
                        .WithOne()
                        .HasForeignKey("FileMaster", "PropertyAddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApplicationUser", "ValidationPerson")
                        .WithMany()
                        .HasForeignKey("ValidationPersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CapturePerson");

                    b.Navigation("PropertyAddress");

                    b.Navigation("ValidationPerson");
                });

            modelBuilder.Entity("GovernmentWaterControlArea", b =>
                {
                    b.HasOne("Address", "WaterControlAddress")
                        .WithMany()
                        .HasForeignKey("WaterControlAddressAddressId");

                    b.Navigation("WaterControlAddress");
                });

            modelBuilder.Entity("Irrigation", b =>
                {
                    b.HasOne("Property", "Property")
                        .WithMany()
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Property");
                });

            modelBuilder.Entity("IrrigationBoard", b =>
                {
                    b.HasOne("Address", "IrrigationBoardAddress")
                        .WithMany()
                        .HasForeignKey("IrrigationBoardAddressAddressId");

                    b.Navigation("IrrigationBoardAddress");
                });

            modelBuilder.Entity("LetterIssuance", b =>
                {
                    b.HasOne("LetterType", "LetterType")
                        .WithMany()
                        .HasForeignKey("LetterTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PropertyOwner", "PropertyOwner")
                        .WithMany()
                        .HasForeignKey("PropertyOwnerOwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LetterType");

                    b.Navigation("PropertyOwner");
                });

            modelBuilder.Entity("Property", b =>
                {
                    b.HasOne("Address", "PropertyAddress")
                        .WithMany()
                        .HasForeignKey("PropertyAddressAddressId");

                    b.Navigation("PropertyAddress");
                });

            modelBuilder.Entity("PropertyOwner", b =>
                {
                    b.HasOne("Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CustomerType", "CustomerType")
                        .WithMany()
                        .HasForeignKey("CustomerTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");

                    b.Navigation("CustomerType");
                });

            modelBuilder.Entity("PropertyOwnership", b =>
                {
                    b.HasOne("Property", "Property")
                        .WithMany("PropertyOwnerships")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PropertyOwner", "PropertyOwner")
                        .WithMany("PropertyOwnerships")
                        .HasForeignKey("PropertyOwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Property");

                    b.Navigation("PropertyOwner");
                });

            modelBuilder.Entity("Storing", b =>
                {
                    b.HasOne("Period", "Period")
                        .WithMany()
                        .HasForeignKey("PeriodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Property", "Property")
                        .WithMany()
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("River", "RiverOrStream")
                        .WithMany()
                        .HasForeignKey("RiverOrStreamRiverId");

                    b.Navigation("Period");

                    b.Navigation("Property");

                    b.Navigation("RiverOrStream");
                });

            modelBuilder.Entity("Property", b =>
                {
                    b.Navigation("PropertyOwnerships");
                });

            modelBuilder.Entity("PropertyOwner", b =>
                {
                    b.Navigation("PropertyOwnerships");
                });
#pragma warning restore 612, 618
        }
    }
}
