{{- if not .Values.secrets.useKeyVault }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dwa-vv.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dwa-vv.labels" . | nindent 4 }}
type: Opaque
stringData:
  ConnectionStrings__Default: {{ .Values.secrets.connectionString | quote }}
  Identity__InitialDemoPassword: {{ .Values.secrets.demoPwd | quote }}
  Portal__AllowPlaintextIdentityNumber: {{ .Values.secrets.popiaAck | quote }}
{{- end }}
