apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "dwa-vv.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dwa-vv.labels" . | nindent 4 }}
  {{- if .Values.secrets.useKeyVault }}
  annotations:
    azure.workload.identity/client-id: {{ .Values.workloadIdentity.clientId | quote }}
    azure.workload.identity/tenant-id: {{ .Values.workloadIdentity.tenantId | quote }}
  {{- end }}
